
// Objective-C API for talking to the following Go packages
//
//	gomobile_sample
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Samplefunc_FRAMEWORK_H__
#define __Samplefunc_FRAMEWORK_H__

#include "Samplefunc.objc.h"
#include "Universe.objc.h"

#endif
